"""marketing module: goals, briefs, proposals, campaigns, plan items, decisions, autopilot policy

Revision ID: 1a7d006e5a8c
Revises: 94c0c13d5661
Create Date: 2026-07-31 14:16:07.777593

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1a7d006e5a8c'
down_revision: str | Sequence[str] | None = '94c0c13d5661'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marketing_goals',
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint("slug in ('more_sales', 'more_messages_bookings', 'more_website_traffic', 'more_followers_engagement', 'brand_awareness', 'product_service_launch', 'offer_announcement', 'product_education', 'retargeting', 'seasonal_evergreen_promotion')", name=op.f('ck_marketing_goals_ck_marketing_goal_slug')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_marketing_goals')),
    sa.UniqueConstraint('slug', name=op.f('uq_marketing_goals_slug'))
    )
    op.create_table('marketing_briefs',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('goal_id', sa.UUID(), nullable=False),
    sa.Column('what_to_promote', sa.Text(), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('target_platforms', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("mode in ('manual', 'guided', 'autopilot')", name=op.f('ck_marketing_briefs_ck_marketing_brief_mode')),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_marketing_briefs_created_by_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['goal_id'], ['marketing_goals.id'], name=op.f('fk_marketing_briefs_goal_id_marketing_goals'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='fk_marketing_briefs_organization_id_organizations', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_marketing_briefs_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_marketing_briefs'))
    )
    op.create_index(op.f('ix_marketing_briefs_organization_id'), 'marketing_briefs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_marketing_briefs_workspace_id'), 'marketing_briefs', ['workspace_id'], unique=False)
    op.create_table('campaign_proposals',
    sa.Column('brief_id', sa.UUID(), nullable=False),
    sa.Column('objective', sa.String(length=300), nullable=False),
    sa.Column('assumptions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('plan_summary', sa.Text(), nullable=False),
    sa.Column('estimated_cost', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brief_id'], ['marketing_briefs.id'], name=op.f('fk_campaign_proposals_brief_id_marketing_briefs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaign_proposals'))
    )
    op.create_index(op.f('ix_campaign_proposals_brief_id'), 'campaign_proposals', ['brief_id'], unique=False)
    op.create_table('campaigns',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('proposal_id', sa.UUID(), nullable=False),
    sa.Column('approved_by_user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('temporal_workflow_id', sa.String(length=200), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("status in ('planning', 'active', 'completed', 'cancelled')", name=op.f('ck_campaigns_ck_campaign_status')),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], name=op.f('fk_campaigns_approved_by_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='fk_campaigns_organization_id_organizations', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proposal_id'], ['campaign_proposals.id'], name=op.f('fk_campaigns_proposal_id_campaign_proposals'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_campaigns_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaigns')),
    sa.UniqueConstraint('proposal_id', name=op.f('uq_campaigns_proposal_id')),
    sa.UniqueConstraint('temporal_workflow_id', name=op.f('uq_campaigns_temporal_workflow_id'))
    )
    op.create_index(op.f('ix_campaigns_organization_id'), 'campaigns', ['organization_id'], unique=False)
    op.create_index(op.f('ix_campaigns_workspace_id'), 'campaigns', ['workspace_id'], unique=False)
    op.create_table('autopilot_policies',
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('allowed_platforms', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('max_total_spend', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('blocked_topics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('posting_window_start_hour', sa.Integer(), nullable=False),
    sa.Column('posting_window_end_hour', sa.Integer(), nullable=False),
    sa.Column('kill_switch_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_autopilot_policies_campaign_id_campaigns'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_autopilot_policies_created_by_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_autopilot_policies')),
    sa.UniqueConstraint('campaign_id', name='uq_autopilot_policy_campaign')
    )
    op.create_table('campaign_plan_items',
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('brief_text', sa.Text(), nullable=False),
    sa.Column('platform_connection_id', sa.UUID(), nullable=True),
    sa.Column('content_item_id', sa.UUID(), nullable=True),
    sa.Column('generation_job_id', sa.UUID(), nullable=True),
    sa.Column('publication_plan_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_campaign_plan_items_campaign_id_campaigns'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['content_item_id'], ['content_items.id'], name=op.f('fk_campaign_plan_items_content_item_id_content_items'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['generation_job_id'], ['generation_jobs.id'], name=op.f('fk_campaign_plan_items_generation_job_id_generation_jobs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['platform_connection_id'], ['platform_connections.id'], name=op.f('fk_campaign_plan_items_platform_connection_id_platform_connections'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['publication_plan_id'], ['publication_plans.id'], name=op.f('fk_campaign_plan_items_publication_plan_id_publication_plans'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaign_plan_items'))
    )
    op.create_index(op.f('ix_campaign_plan_items_campaign_id'), 'campaign_plan_items', ['campaign_id'], unique=False)
    op.create_table('campaign_decisions',
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('plan_item_id', sa.UUID(), nullable=True),
    sa.Column('decision_type', sa.String(length=30), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint("decision_type in ('proposal_generated', 'autopilot_proceed', 'autopilot_skipped', 'autopilot_halted')", name=op.f('ck_campaign_decisions_ck_campaign_decision_type')),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_campaign_decisions_campaign_id_campaigns'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_item_id'], ['campaign_plan_items.id'], name=op.f('fk_campaign_decisions_plan_item_id_campaign_plan_items'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaign_decisions'))
    )
    op.create_index(op.f('ix_campaign_decisions_campaign_id'), 'campaign_decisions', ['campaign_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_campaign_decisions_campaign_id'), table_name='campaign_decisions')
    op.drop_table('campaign_decisions')
    op.drop_index(op.f('ix_campaign_plan_items_campaign_id'), table_name='campaign_plan_items')
    op.drop_table('campaign_plan_items')
    op.drop_table('autopilot_policies')
    op.drop_index(op.f('ix_campaigns_workspace_id'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_organization_id'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_campaign_proposals_brief_id'), table_name='campaign_proposals')
    op.drop_table('campaign_proposals')
    op.drop_index(op.f('ix_marketing_briefs_workspace_id'), table_name='marketing_briefs')
    op.drop_index(op.f('ix_marketing_briefs_organization_id'), table_name='marketing_briefs')
    op.drop_table('marketing_briefs')
    op.drop_table('marketing_goals')
    # ### end Alembic commands ###
