"""generation_jobs: track cost_reservation_id

Revision ID: 228332898f6b
Revises: bb53c8b3ac87
Create Date: 2026-07-31 08:14:16.802087

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '228332898f6b'
down_revision: str | Sequence[str] | None = 'bb53c8b3ac87'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generation_jobs', sa.Column('cost_reservation_id', sa.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk_generation_jobs_cost_reservation_id_cost_reservations'), 'generation_jobs', 'cost_reservations', ['cost_reservation_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_generation_jobs_cost_reservation_id_cost_reservations'), 'generation_jobs', type_='foreignkey')
    op.drop_column('generation_jobs', 'cost_reservation_id')
    # ### end Alembic commands ###
