"""governance module: agent/tool registries, tool approvals, policy and moderation decisions

Revision ID: 24a7cd61ae9d
Revises: bd6a0464dfe7
Create Date: 2026-07-31 18:01:32.722703

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '24a7cd61ae9d'
down_revision: str | Sequence[str] | None = 'bd6a0464dfe7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_registrations',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('mcp_domain', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("mcp_domain in ('knowledge', 'marketing', 'planning', 'commerce', 'generation', 'audio', 'connections', 'publishing', 'analytics', 'distribution', 'billing', 'support')", name=op.f('ck_agent_registrations_ck_agent_registration_mcp_domain')),
    sa.CheckConstraint("name in ('marketing_manager', 'campaign_planner', 'creation_coordinator', 'publishing', 'analytics_recommendation', 'ecommerce', 'audio_guide', 'support')", name=op.f('ck_agent_registrations_ck_agent_registration_name')),
    sa.CheckConstraint("status in ('active', 'disabled')", name=op.f('ck_agent_registrations_ck_agent_registration_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_registrations')),
    sa.UniqueConstraint('name', name=op.f('uq_agent_registrations_name'))
    )
    op.create_table('moderation_decisions',
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('correlation_id', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('decision', sa.String(length=10), nullable=False),
    sa.Column('detected_patterns', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('content_excerpt', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint("decision in ('allowed', 'blocked')", name=op.f('ck_moderation_decisions_ck_moderation_decision_decision')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='fk_moderation_decisions_organization_id_organizations', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_moderation_decisions'))
    )
    op.create_index(op.f('ix_moderation_decisions_correlation_id'), 'moderation_decisions', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_moderation_decisions_organization_id'), 'moderation_decisions', ['organization_id'], unique=False)
    op.create_table('tool_registrations',
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("risk_level in ('low', 'medium', 'high')", name=op.f('ck_tool_registrations_ck_tool_registration_risk_level')),
    sa.CheckConstraint("status in ('active', 'disabled')", name=op.f('ck_tool_registrations_ck_tool_registration_status')),
    sa.ForeignKeyConstraint(['agent_id'], ['agent_registrations.id'], name=op.f('fk_tool_registrations_agent_id_agent_registrations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tool_registrations')),
    sa.UniqueConstraint('name', 'version', name='uq_tool_registration_name_version')
    )
    op.create_index(op.f('ix_tool_registrations_agent_id'), 'tool_registrations', ['agent_id'], unique=False)
    op.create_table('policy_decision_references',
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('tool_registration_id', sa.UUID(), nullable=True),
    sa.Column('correlation_id', sa.String(length=100), nullable=True),
    sa.Column('policy_path', sa.String(length=200), nullable=False),
    sa.Column('decision', sa.String(length=10), nullable=False),
    sa.Column('reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('input_digest', sa.String(length=64), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint("decision in ('allow', 'deny')", name=op.f('ck_policy_decision_references_ck_policy_decision_reference_decision')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='fk_policy_decision_references_organization_id_organizations', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tool_registration_id'], ['tool_registrations.id'], name=op.f('fk_policy_decision_references_tool_registration_id_tool_registrations'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_policy_decision_references'))
    )
    op.create_index(op.f('ix_policy_decision_references_correlation_id'), 'policy_decision_references', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_policy_decision_references_organization_id'), 'policy_decision_references', ['organization_id'], unique=False)
    op.create_table('tool_approvals',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('tool_registration_id', sa.UUID(), nullable=False),
    sa.Column('requested_by_user_id', sa.UUID(), nullable=True),
    sa.Column('approved_by_user_id', sa.UUID(), nullable=True),
    sa.Column('payload_digest', sa.String(length=64), nullable=False),
    sa.Column('destination', sa.String(length=300), nullable=True),
    sa.Column('cost', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('correlation_id', sa.String(length=100), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("status in ('pending', 'approved', 'rejected', 'expired', 'used')", name=op.f('ck_tool_approvals_ck_tool_approval_status')),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], name=op.f('fk_tool_approvals_approved_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='fk_tool_approvals_organization_id_organizations', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], name=op.f('fk_tool_approvals_requested_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tool_registration_id'], ['tool_registrations.id'], name=op.f('fk_tool_approvals_tool_registration_id_tool_registrations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_tool_approvals_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tool_approvals'))
    )
    op.create_index(op.f('ix_tool_approvals_correlation_id'), 'tool_approvals', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_tool_approvals_organization_id'), 'tool_approvals', ['organization_id'], unique=False)
    op.create_index(op.f('ix_tool_approvals_tool_registration_id'), 'tool_approvals', ['tool_registration_id'], unique=False)
    op.create_index(op.f('ix_tool_approvals_workspace_id'), 'tool_approvals', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tool_approvals_workspace_id'), table_name='tool_approvals')
    op.drop_index(op.f('ix_tool_approvals_tool_registration_id'), table_name='tool_approvals')
    op.drop_index(op.f('ix_tool_approvals_organization_id'), table_name='tool_approvals')
    op.drop_index(op.f('ix_tool_approvals_correlation_id'), table_name='tool_approvals')
    op.drop_table('tool_approvals')
    op.drop_index(op.f('ix_policy_decision_references_organization_id'), table_name='policy_decision_references')
    op.drop_index(op.f('ix_policy_decision_references_correlation_id'), table_name='policy_decision_references')
    op.drop_table('policy_decision_references')
    op.drop_index(op.f('ix_tool_registrations_agent_id'), table_name='tool_registrations')
    op.drop_table('tool_registrations')
    op.drop_index(op.f('ix_moderation_decisions_organization_id'), table_name='moderation_decisions')
    op.drop_index(op.f('ix_moderation_decisions_correlation_id'), table_name='moderation_decisions')
    op.drop_table('moderation_decisions')
    op.drop_table('agent_registrations')
    # ### end Alembic commands ###
