"""commerce_add_product_categories

Revision ID: 4c84443c301a
Revises: 4731ddc445eb
Create Date: 2026-09-03 15:38:09.582763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c84443c301a'
down_revision: Union[str, Sequence[str], None] = '4731ddc445eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_categories',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('store_connection_id', sa.UUID(), nullable=False),
    sa.Column('external_category_id', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('parent_external_category_id', sa.String(length=200), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='fk_product_categories_organization_id_organizations', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_connection_id'], ['store_connections.id'], name=op.f('fk_product_categories_store_connection_id_store_connections'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_product_categories_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_categories')),
    sa.UniqueConstraint('store_connection_id', 'external_category_id', name='uq_category_conn_external_id')
    )
    op.create_index(op.f('ix_product_categories_organization_id'), 'product_categories', ['organization_id'], unique=False)
    op.create_index(op.f('ix_product_categories_store_connection_id'), 'product_categories', ['store_connection_id'], unique=False)
    op.create_index(op.f('ix_product_categories_workspace_id'), 'product_categories', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_categories_workspace_id'), table_name='product_categories')
    op.drop_index(op.f('ix_product_categories_store_connection_id'), table_name='product_categories')
    op.drop_index(op.f('ix_product_categories_organization_id'), table_name='product_categories')
    op.drop_table('product_categories')
    # ### end Alembic commands ###
