"""billing module: subscription plans, subscriptions, cost reservations, usage ledger

Revision ID: 7a49b971a729
Revises: ca108b752a0e
Create Date: 2026-07-30 15:49:12.474936

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7a49b971a729'
down_revision: str | Sequence[str] | None = 'ca108b752a0e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_plans',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('monthly_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('monthly_credit_allowance', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscription_plans')),
    sa.UniqueConstraint('name', name=op.f('uq_subscription_plans_name')),
    sa.UniqueConstraint('slug', name=op.f('uq_subscription_plans_slug'))
    )
    op.create_table('customer_subscriptions',
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('credit_balance', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='fk_customer_subscriptions_organization_id_organizations', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plans.id'], name=op.f('fk_customer_subscriptions_plan_id_subscription_plans'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customer_subscriptions')),
    sa.UniqueConstraint('organization_id', name='uq_customer_subscription_organization')
    )
    op.create_index(op.f('ix_customer_subscriptions_organization_id'), 'customer_subscriptions', ['organization_id'], unique=False)
    op.create_table('cost_reservations',
    sa.Column('subscription_id', sa.UUID(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=200), nullable=False),
    sa.Column('reference', sa.String(length=300), nullable=False),
    sa.Column('reserved_amount', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('settled_amount', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("status in ('reserved', 'settled', 'released')", name=op.f('ck_cost_reservations_ck_cost_reservation_status')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='fk_cost_reservations_organization_id_organizations', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscription_id'], ['customer_subscriptions.id'], name=op.f('fk_cost_reservations_subscription_id_customer_subscriptions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cost_reservations')),
    sa.UniqueConstraint('idempotency_key', name='uq_cost_reservation_idempotency_key')
    )
    op.create_index(op.f('ix_cost_reservations_organization_id'), 'cost_reservations', ['organization_id'], unique=False)
    op.create_index(op.f('ix_cost_reservations_subscription_id'), 'cost_reservations', ['subscription_id'], unique=False)
    op.create_table('usage_ledger_entries',
    sa.Column('subscription_id', sa.UUID(), nullable=False),
    sa.Column('reservation_id', sa.UUID(), nullable=True),
    sa.Column('entry_type', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("entry_type in ('allocation','reservation','consumption','release','adjustment','refund','overage')", name=op.f('ck_usage_ledger_entries_ck_usage_ledger_entry_type')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='fk_usage_ledger_entries_organization_id_organizations', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reservation_id'], ['cost_reservations.id'], name=op.f('fk_usage_ledger_entries_reservation_id_cost_reservations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subscription_id'], ['customer_subscriptions.id'], name=op.f('fk_usage_ledger_entries_subscription_id_customer_subscriptions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usage_ledger_entries'))
    )
    op.create_index(op.f('ix_usage_ledger_entries_organization_id'), 'usage_ledger_entries', ['organization_id'], unique=False)
    op.create_index(op.f('ix_usage_ledger_entries_reservation_id'), 'usage_ledger_entries', ['reservation_id'], unique=False)
    op.create_index(op.f('ix_usage_ledger_entries_subscription_id'), 'usage_ledger_entries', ['subscription_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usage_ledger_entries_subscription_id'), table_name='usage_ledger_entries')
    op.drop_index(op.f('ix_usage_ledger_entries_reservation_id'), table_name='usage_ledger_entries')
    op.drop_index(op.f('ix_usage_ledger_entries_organization_id'), table_name='usage_ledger_entries')
    op.drop_table('usage_ledger_entries')
    op.drop_index(op.f('ix_cost_reservations_subscription_id'), table_name='cost_reservations')
    op.drop_index(op.f('ix_cost_reservations_organization_id'), table_name='cost_reservations')
    op.drop_table('cost_reservations')
    op.drop_index(op.f('ix_customer_subscriptions_organization_id'), table_name='customer_subscriptions')
    op.drop_table('customer_subscriptions')
    op.drop_table('subscription_plans')
    # ### end Alembic commands ###
