"""publishing module: connections, capabilities, publication plans, attempts, reconciliation

Revision ID: 94c0c13d5661
Revises: 228332898f6b
Create Date: 2026-07-31 13:08:59.032646

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '94c0c13d5661'
down_revision: str | Sequence[str] | None = '228332898f6b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_connections',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('connected_by_user_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('external_account_id', sa.String(length=200), nullable=False),
    sa.Column('external_account_name', sa.String(length=300), nullable=False),
    sa.Column('access_token_secret_ref', sa.String(length=300), nullable=False),
    sa.Column('refresh_token_secret_ref', sa.String(length=300), nullable=True),
    sa.Column('scopes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_refreshed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("platform in ('facebook', 'instagram', 'tiktok', 'youtube')", name=op.f('ck_platform_connections_ck_platform_connection_platform')),
    sa.CheckConstraint("status in ('connected', 'disconnected', 'error', 'token_expired')", name=op.f('ck_platform_connections_ck_platform_connection_status')),
    sa.ForeignKeyConstraint(['connected_by_user_id'], ['users.id'], name=op.f('fk_platform_connections_connected_by_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='fk_platform_connections_organization_id_organizations', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_platform_connections_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_platform_connections'))
    )
    op.create_index(op.f('ix_platform_connections_organization_id'), 'platform_connections', ['organization_id'], unique=False)
    op.create_index(op.f('ix_platform_connections_workspace_id'), 'platform_connections', ['workspace_id'], unique=False)
    op.create_table('effective_capabilities',
    sa.Column('platform_connection_id', sa.UUID(), nullable=False),
    sa.Column('capability', sa.String(length=100), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['platform_connection_id'], ['platform_connections.id'], name=op.f('fk_effective_capabilities_platform_connection_id_platform_connections'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_effective_capabilities')),
    sa.UniqueConstraint('platform_connection_id', 'capability', name='uq_effective_capability_conn_cap')
    )
    op.create_index(op.f('ix_effective_capabilities_platform_connection_id'), 'effective_capabilities', ['platform_connection_id'], unique=False)
    op.create_table('publication_plans',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('content_item_id', sa.UUID(), nullable=False),
    sa.Column('platform_connection_id', sa.UUID(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('approved_by_user_id', sa.UUID(), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('temporal_workflow_id', sa.String(length=200), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("status in ('draft', 'pending_approval', 'approved', 'publishing', 'published', 'failed', 'rejected', 'cancelled')", name=op.f('ck_publication_plans_ck_publication_plan_status')),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], name=op.f('fk_publication_plans_approved_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['content_item_id'], ['content_items.id'], name=op.f('fk_publication_plans_content_item_id_content_items'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_publication_plans_created_by_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='fk_publication_plans_organization_id_organizations', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['platform_connection_id'], ['platform_connections.id'], name=op.f('fk_publication_plans_platform_connection_id_platform_connections'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_publication_plans_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_publication_plans')),
    sa.UniqueConstraint('temporal_workflow_id', name=op.f('uq_publication_plans_temporal_workflow_id'))
    )
    op.create_index(op.f('ix_publication_plans_content_item_id'), 'publication_plans', ['content_item_id'], unique=False)
    op.create_index(op.f('ix_publication_plans_organization_id'), 'publication_plans', ['organization_id'], unique=False)
    op.create_index(op.f('ix_publication_plans_workspace_id'), 'publication_plans', ['workspace_id'], unique=False)
    op.create_table('publication_attempts',
    sa.Column('publication_plan_id', sa.UUID(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('external_post_id', sa.String(length=300), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint("status in ('dispatched', 'succeeded', 'failed')", name=op.f('ck_publication_attempts_ck_publication_attempt_status')),
    sa.ForeignKeyConstraint(['publication_plan_id'], ['publication_plans.id'], name=op.f('fk_publication_attempts_publication_plan_id_publication_plans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_publication_attempts')),
    sa.UniqueConstraint('publication_plan_id', 'attempt_number', name='uq_publication_attempt_plan_number')
    )
    op.create_index(op.f('ix_publication_attempts_publication_plan_id'), 'publication_attempts', ['publication_plan_id'], unique=False)
    op.create_table('reconciliations',
    sa.Column('publication_attempt_id', sa.UUID(), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('matches_expected', sa.Boolean(), nullable=False),
    sa.Column('external_status', sa.String(length=100), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['publication_attempt_id'], ['publication_attempts.id'], name=op.f('fk_reconciliations_publication_attempt_id_publication_attempts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reconciliations'))
    )
    op.create_index(op.f('ix_reconciliations_publication_attempt_id'), 'reconciliations', ['publication_attempt_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reconciliations_publication_attempt_id'), table_name='reconciliations')
    op.drop_table('reconciliations')
    op.drop_index(op.f('ix_publication_attempts_publication_plan_id'), table_name='publication_attempts')
    op.drop_table('publication_attempts')
    op.drop_index(op.f('ix_publication_plans_workspace_id'), table_name='publication_plans')
    op.drop_index(op.f('ix_publication_plans_organization_id'), table_name='publication_plans')
    op.drop_index(op.f('ix_publication_plans_content_item_id'), table_name='publication_plans')
    op.drop_table('publication_plans')
    op.drop_index(op.f('ix_effective_capabilities_platform_connection_id'), table_name='effective_capabilities')
    op.drop_table('effective_capabilities')
    op.drop_index(op.f('ix_platform_connections_workspace_id'), table_name='platform_connections')
    op.drop_index(op.f('ix_platform_connections_organization_id'), table_name='platform_connections')
    op.drop_table('platform_connections')
    # ### end Alembic commands ###
