"""analytics module: metric definitions, snapshots, conversion events, recommendations, outcomes, experiments, strategy versions, model versions

Revision ID: a00ec5567d1b
Revises: d2065f1248fe
Create Date: 2026-07-31 15:13:33.299035

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a00ec5567d1b'
down_revision: str | Sequence[str] | None = 'd2065f1248fe'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metric_definitions',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('unit', sa.String(length=30), nullable=False),
    sa.Column('scope', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_metric_definitions')),
    sa.UniqueConstraint('name', name=op.f('uq_metric_definitions_name'))
    )
    op.create_table('model_versions',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_versions')),
    sa.UniqueConstraint('name', name=op.f('uq_model_versions_name'))
    )
    op.create_table('strategy_versions',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_strategy_versions')),
    sa.UniqueConstraint('name', name=op.f('uq_strategy_versions_name'))
    )
    op.create_table('recommendations',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('strategy_version_id', sa.UUID(), nullable=False),
    sa.Column('recommendation_type', sa.String(length=50), nullable=False),
    sa.Column('objective', sa.String(length=300), nullable=False),
    sa.Column('score', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('confidence', sa.String(length=20), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('data_window_days', sa.Integer(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='fk_recommendations_organization_id_organizations', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['strategy_version_id'], ['strategy_versions.id'], name=op.f('fk_recommendations_strategy_version_id_strategy_versions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_recommendations_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recommendations'))
    )
    op.create_index(op.f('ix_recommendations_organization_id'), 'recommendations', ['organization_id'], unique=False)
    op.create_index(op.f('ix_recommendations_workspace_id'), 'recommendations', ['workspace_id'], unique=False)
    op.create_table('recommendation_outcomes',
    sa.Column('recommendation_id', sa.UUID(), nullable=False),
    sa.Column('outcome', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint("outcome in ('acted_on', 'dismissed', 'expired')", name=op.f('ck_recommendation_outcomes_ck_recommendation_outcome_status')),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], name=op.f('fk_recommendation_outcomes_recommendation_id_recommendations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_recommendation_outcomes_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recommendation_outcomes'))
    )
    op.create_index(op.f('ix_recommendation_outcomes_recommendation_id'), 'recommendation_outcomes', ['recommendation_id'], unique=False)
    op.create_table('experiments',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('campaign_a_id', sa.UUID(), nullable=False),
    sa.Column('campaign_b_id', sa.UUID(), nullable=False),
    sa.Column('metric_definition_id', sa.UUID(), nullable=False),
    sa.Column('winner', sa.String(length=20), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result_summary', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("winner in ('a', 'b', 'inconclusive')", name=op.f('ck_experiments_ck_experiment_winner')),
    sa.ForeignKeyConstraint(['campaign_a_id'], ['campaigns.id'], name=op.f('fk_experiments_campaign_a_id_campaigns'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['campaign_b_id'], ['campaigns.id'], name=op.f('fk_experiments_campaign_b_id_campaigns'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['metric_definition_id'], ['metric_definitions.id'], name=op.f('fk_experiments_metric_definition_id_metric_definitions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='fk_experiments_organization_id_organizations', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_experiments_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_experiments'))
    )
    op.create_index(op.f('ix_experiments_organization_id'), 'experiments', ['organization_id'], unique=False)
    op.create_index(op.f('ix_experiments_workspace_id'), 'experiments', ['workspace_id'], unique=False)
    op.create_table('conversion_events',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('campaign_plan_item_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consent_confirmed', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_plan_item_id'], ['campaign_plan_items.id'], name=op.f('fk_conversion_events_campaign_plan_item_id_campaign_plan_items'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='fk_conversion_events_organization_id_organizations', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_conversion_events_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversion_events'))
    )
    op.create_index(op.f('ix_conversion_events_organization_id'), 'conversion_events', ['organization_id'], unique=False)
    op.create_index(op.f('ix_conversion_events_workspace_id'), 'conversion_events', ['workspace_id'], unique=False)
    op.create_table('metric_snapshots',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('metric_definition_id', sa.UUID(), nullable=False),
    sa.Column('publication_attempt_id', sa.UUID(), nullable=True),
    sa.Column('campaign_plan_item_id', sa.UUID(), nullable=True),
    sa.Column('raw_provider_name', sa.String(length=100), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('normalized_value', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('measurement_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('collection_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attribution_window_days', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_plan_item_id'], ['campaign_plan_items.id'], name=op.f('fk_metric_snapshots_campaign_plan_item_id_campaign_plan_items'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['metric_definition_id'], ['metric_definitions.id'], name=op.f('fk_metric_snapshots_metric_definition_id_metric_definitions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='fk_metric_snapshots_organization_id_organizations', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['publication_attempt_id'], ['publication_attempts.id'], name=op.f('fk_metric_snapshots_publication_attempt_id_publication_attempts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_metric_snapshots_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_metric_snapshots'))
    )
    op.create_index(op.f('ix_metric_snapshots_campaign_plan_item_id'), 'metric_snapshots', ['campaign_plan_item_id'], unique=False)
    op.create_index(op.f('ix_metric_snapshots_organization_id'), 'metric_snapshots', ['organization_id'], unique=False)
    op.create_index(op.f('ix_metric_snapshots_publication_attempt_id'), 'metric_snapshots', ['publication_attempt_id'], unique=False)
    op.create_index(op.f('ix_metric_snapshots_workspace_id'), 'metric_snapshots', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_metric_snapshots_workspace_id'), table_name='metric_snapshots')
    op.drop_index(op.f('ix_metric_snapshots_publication_attempt_id'), table_name='metric_snapshots')
    op.drop_index(op.f('ix_metric_snapshots_organization_id'), table_name='metric_snapshots')
    op.drop_index(op.f('ix_metric_snapshots_campaign_plan_item_id'), table_name='metric_snapshots')
    op.drop_table('metric_snapshots')
    op.drop_index(op.f('ix_conversion_events_workspace_id'), table_name='conversion_events')
    op.drop_index(op.f('ix_conversion_events_organization_id'), table_name='conversion_events')
    op.drop_table('conversion_events')
    op.drop_index(op.f('ix_experiments_workspace_id'), table_name='experiments')
    op.drop_index(op.f('ix_experiments_organization_id'), table_name='experiments')
    op.drop_table('experiments')
    op.drop_index(op.f('ix_recommendation_outcomes_recommendation_id'), table_name='recommendation_outcomes')
    op.drop_table('recommendation_outcomes')
    op.drop_index(op.f('ix_recommendations_workspace_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_organization_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_table('strategy_versions')
    op.drop_table('model_versions')
    op.drop_table('metric_definitions')
    # ### end Alembic commands ###
