"""campaign_proposals: add plan_items_draft

Revision ID: b5358aeb361b
Revises: 1a7d006e5a8c
Create Date: 2026-07-31 14:18:11.320829

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b5358aeb361b'
down_revision: str | Sequence[str] | None = '1a7d006e5a8c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaign_proposals', sa.Column('plan_items_draft', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaign_proposals', 'plan_items_draft')
    # ### end Alembic commands ###
