"""creation module: content generation lifecycle (items, jobs, attempts, revisions, reviews, packages, recipes)

Revision ID: bb53c8b3ac87
Revises: c8ca41ab4d64
Create Date: 2026-07-31 08:08:52.860214

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'bb53c8b3ac87'
down_revision: str | Sequence[str] | None = 'c8ca41ab4d64'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_recipes',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('content_type', sa.String(length=20), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('estimated_cost', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("content_type in ('text', 'image')", name=op.f('ck_content_recipes_ck_content_recipe_content_type')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_recipes')),
    sa.UniqueConstraint('name', name=op.f('uq_content_recipes_name'))
    )
    op.create_table('content_items',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('brand_profile_id', sa.UUID(), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('content_type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("content_type in ('text', 'image')", name=op.f('ck_content_items_ck_content_item_content_type')),
    sa.CheckConstraint("status in ('draft', 'in_review', 'approved', 'rejected')", name=op.f('ck_content_items_ck_content_item_status')),
    sa.ForeignKeyConstraint(['brand_profile_id'], ['brand_profiles.id'], name=op.f('fk_content_items_brand_profile_id_brand_profiles'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_content_items_created_by_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='fk_content_items_organization_id_organizations', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_content_items_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_items'))
    )
    op.create_index(op.f('ix_content_items_organization_id'), 'content_items', ['organization_id'], unique=False)
    op.create_index(op.f('ix_content_items_workspace_id'), 'content_items', ['workspace_id'], unique=False)
    op.create_table('generation_jobs',
    sa.Column('content_item_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('recipe_id', sa.UUID(), nullable=False),
    sa.Column('requested_by_user_id', sa.UUID(), nullable=False),
    sa.Column('subscription_id', sa.UUID(), nullable=False),
    sa.Column('brief_text', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('temporal_workflow_id', sa.String(length=200), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("status in ('pending', 'generating', 'quality_gate_failed', 'awaiting_review', 'approved', 'rejected', 'failed')", name=op.f('ck_generation_jobs_ck_generation_job_status')),
    sa.ForeignKeyConstraint(['content_item_id'], ['content_items.id'], name=op.f('fk_generation_jobs_content_item_id_content_items'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='fk_generation_jobs_organization_id_organizations', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipe_id'], ['content_recipes.id'], name=op.f('fk_generation_jobs_recipe_id_content_recipes'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], name=op.f('fk_generation_jobs_requested_by_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['subscription_id'], ['customer_subscriptions.id'], name=op.f('fk_generation_jobs_subscription_id_customer_subscriptions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_generation_jobs_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_generation_jobs')),
    sa.UniqueConstraint('temporal_workflow_id', name=op.f('uq_generation_jobs_temporal_workflow_id'))
    )
    op.create_index(op.f('ix_generation_jobs_content_item_id'), 'generation_jobs', ['content_item_id'], unique=False)
    op.create_index(op.f('ix_generation_jobs_organization_id'), 'generation_jobs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_generation_jobs_workspace_id'), 'generation_jobs', ['workspace_id'], unique=False)
    op.create_table('generation_attempts',
    sa.Column('generation_job_id', sa.UUID(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('actual_cost', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint("status in ('dispatched', 'succeeded', 'failed')", name=op.f('ck_generation_attempts_ck_generation_attempt_status')),
    sa.ForeignKeyConstraint(['generation_job_id'], ['generation_jobs.id'], name=op.f('fk_generation_attempts_generation_job_id_generation_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_generation_attempts')),
    sa.UniqueConstraint('generation_job_id', 'attempt_number', name='uq_generation_attempt_job_number')
    )
    op.create_index(op.f('ix_generation_attempts_generation_job_id'), 'generation_attempts', ['generation_job_id'], unique=False)
    op.create_table('content_revisions',
    sa.Column('content_item_id', sa.UUID(), nullable=False),
    sa.Column('generation_attempt_id', sa.UUID(), nullable=True),
    sa.Column('asset_id', sa.UUID(), nullable=True),
    sa.Column('revision_number', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('text_body', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind in ('draft_preview', 'final_render')", name=op.f('ck_content_revisions_ck_content_revision_kind')),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_content_revisions_asset_id_assets'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['content_item_id'], ['content_items.id'], name=op.f('fk_content_revisions_content_item_id_content_items'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['generation_attempt_id'], ['generation_attempts.id'], name=op.f('fk_content_revisions_generation_attempt_id_generation_attempts'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_revisions')),
    sa.UniqueConstraint('content_item_id', 'revision_number', name='uq_content_revision_item_number')
    )
    op.create_index(op.f('ix_content_revisions_content_item_id'), 'content_revisions', ['content_item_id'], unique=False)
    op.create_table('content_packages',
    sa.Column('content_item_id', sa.UUID(), nullable=False),
    sa.Column('selected_revision_id', sa.UUID(), nullable=False),
    sa.Column('packaged_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['content_item_id'], ['content_items.id'], name=op.f('fk_content_packages_content_item_id_content_items'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['selected_revision_id'], ['content_revisions.id'], name=op.f('fk_content_packages_selected_revision_id_content_revisions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_packages')),
    sa.UniqueConstraint('content_item_id', name='uq_content_package_item')
    )
    op.create_table('reviews',
    sa.Column('content_revision_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_user_id', sa.UUID(), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint("decision in ('approved', 'rejected')", name=op.f('ck_reviews_ck_review_decision')),
    sa.ForeignKeyConstraint(['content_revision_id'], ['content_revisions.id'], name=op.f('fk_reviews_content_revision_id_content_revisions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_user_id'], ['users.id'], name=op.f('fk_reviews_reviewer_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reviews'))
    )
    op.create_index(op.f('ix_reviews_content_revision_id'), 'reviews', ['content_revision_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviews_content_revision_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_table('content_packages')
    op.drop_index(op.f('ix_content_revisions_content_item_id'), table_name='content_revisions')
    op.drop_table('content_revisions')
    op.drop_index(op.f('ix_generation_attempts_generation_job_id'), table_name='generation_attempts')
    op.drop_table('generation_attempts')
    op.drop_index(op.f('ix_generation_jobs_workspace_id'), table_name='generation_jobs')
    op.drop_index(op.f('ix_generation_jobs_organization_id'), table_name='generation_jobs')
    op.drop_index(op.f('ix_generation_jobs_content_item_id'), table_name='generation_jobs')
    op.drop_table('generation_jobs')
    op.drop_index(op.f('ix_content_items_workspace_id'), table_name='content_items')
    op.drop_index(op.f('ix_content_items_organization_id'), table_name='content_items')
    op.drop_table('content_items')
    op.drop_table('content_recipes')
    # ### end Alembic commands ###
