"""commerce module: store connections, products, webhook deliveries

Revision ID: bd6a0464dfe7
Revises: a00ec5567d1b
Create Date: 2026-07-31 16:29:01.974345

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'bd6a0464dfe7'
down_revision: str | Sequence[str] | None = 'a00ec5567d1b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('store_connections',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('connected_by_user_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('store_domain', sa.String(length=300), nullable=False),
    sa.Column('external_store_id', sa.String(length=200), nullable=False),
    sa.Column('access_token_secret_ref', sa.String(length=300), nullable=False),
    sa.Column('webhook_secret_ref', sa.String(length=300), nullable=False),
    sa.Column('scopes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("platform in ('woocommerce', 'shopify')", name=op.f('ck_store_connections_ck_store_connection_platform')),
    sa.CheckConstraint("status in ('connected', 'disconnected', 'error', 'token_expired')", name=op.f('ck_store_connections_ck_store_connection_status')),
    sa.ForeignKeyConstraint(['connected_by_user_id'], ['users.id'], name=op.f('fk_store_connections_connected_by_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='fk_store_connections_organization_id_organizations', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_store_connections_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_store_connections'))
    )
    op.create_index(op.f('ix_store_connections_organization_id'), 'store_connections', ['organization_id'], unique=False)
    op.create_index(op.f('ix_store_connections_workspace_id'), 'store_connections', ['workspace_id'], unique=False)
    op.create_table('products',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('store_connection_id', sa.UUID(), nullable=False),
    sa.Column('external_product_id', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("status in ('active', 'draft', 'archived')", name=op.f('ck_products_ck_product_status')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='fk_products_organization_id_organizations', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_connection_id'], ['store_connections.id'], name=op.f('fk_products_store_connection_id_store_connections'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_products_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products')),
    sa.UniqueConstraint('store_connection_id', 'external_product_id', name='uq_product_conn_external_id')
    )
    op.create_index(op.f('ix_products_organization_id'), 'products', ['organization_id'], unique=False)
    op.create_index(op.f('ix_products_store_connection_id'), 'products', ['store_connection_id'], unique=False)
    op.create_index(op.f('ix_products_workspace_id'), 'products', ['workspace_id'], unique=False)
    op.create_table('store_capabilities',
    sa.Column('store_connection_id', sa.UUID(), nullable=False),
    sa.Column('capability', sa.String(length=100), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['store_connection_id'], ['store_connections.id'], name=op.f('fk_store_capabilities_store_connection_id_store_connections'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_store_capabilities')),
    sa.UniqueConstraint('store_connection_id', 'capability', name='uq_store_capability_conn_cap')
    )
    op.create_index(op.f('ix_store_capabilities_store_connection_id'), 'store_capabilities', ['store_connection_id'], unique=False)
    op.create_table('store_sync_cursors',
    sa.Column('store_connection_id', sa.UUID(), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('cursor', sa.String(length=500), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['store_connection_id'], ['store_connections.id'], name=op.f('fk_store_sync_cursors_store_connection_id_store_connections'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_store_sync_cursors')),
    sa.UniqueConstraint('store_connection_id', 'resource_type', name='uq_store_sync_cursor_conn_resource')
    )
    op.create_index(op.f('ix_store_sync_cursors_store_connection_id'), 'store_sync_cursors', ['store_connection_id'], unique=False)
    op.create_table('store_webhook_deliveries',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('store_connection_id', sa.UUID(), nullable=False),
    sa.Column('topic', sa.String(length=100), nullable=False),
    sa.Column('external_delivery_id', sa.String(length=200), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('signature_valid', sa.Boolean(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='fk_store_webhook_deliveries_organization_id_organizations', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_connection_id'], ['store_connections.id'], name=op.f('fk_store_webhook_deliveries_store_connection_id_store_connections'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_store_webhook_deliveries_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_store_webhook_deliveries'))
    )
    op.create_index(op.f('ix_store_webhook_deliveries_organization_id'), 'store_webhook_deliveries', ['organization_id'], unique=False)
    op.create_index(op.f('ix_store_webhook_deliveries_store_connection_id'), 'store_webhook_deliveries', ['store_connection_id'], unique=False)
    op.create_index(op.f('ix_store_webhook_deliveries_workspace_id'), 'store_webhook_deliveries', ['workspace_id'], unique=False)
    op.create_table('product_assets',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('external_asset_id', sa.String(length=200), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_assets_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_assets')),
    sa.UniqueConstraint('product_id', 'external_asset_id', name='uq_asset_product_external_id')
    )
    op.create_index(op.f('ix_product_assets_product_id'), 'product_assets', ['product_id'], unique=False)
    op.create_table('product_performance_snapshots',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('raw_provider_name', sa.String(length=100), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('normalized_value', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('measurement_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('collection_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='fk_product_perf_snapshots_organization_id_organizations', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_performance_snapshots_product_id_products'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_product_performance_snapshots_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_performance_snapshots'))
    )
    op.create_index(op.f('ix_product_performance_snapshots_organization_id'), 'product_performance_snapshots', ['organization_id'], unique=False)
    op.create_index(op.f('ix_product_performance_snapshots_product_id'), 'product_performance_snapshots', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_performance_snapshots_workspace_id'), 'product_performance_snapshots', ['workspace_id'], unique=False)
    op.create_table('product_variants',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('external_variant_id', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('sku', sa.String(length=200), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_variants_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_variants')),
    sa.UniqueConstraint('product_id', 'external_variant_id', name='uq_variant_product_external_id')
    )
    op.create_index(op.f('ix_product_variants_product_id'), 'product_variants', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_variants_product_id'), table_name='product_variants')
    op.drop_table('product_variants')
    op.drop_index(op.f('ix_product_performance_snapshots_workspace_id'), table_name='product_performance_snapshots')
    op.drop_index(op.f('ix_product_performance_snapshots_product_id'), table_name='product_performance_snapshots')
    op.drop_index(op.f('ix_product_performance_snapshots_organization_id'), table_name='product_performance_snapshots')
    op.drop_table('product_performance_snapshots')
    op.drop_index(op.f('ix_product_assets_product_id'), table_name='product_assets')
    op.drop_table('product_assets')
    op.drop_index(op.f('ix_store_webhook_deliveries_workspace_id'), table_name='store_webhook_deliveries')
    op.drop_index(op.f('ix_store_webhook_deliveries_store_connection_id'), table_name='store_webhook_deliveries')
    op.drop_index(op.f('ix_store_webhook_deliveries_organization_id'), table_name='store_webhook_deliveries')
    op.drop_table('store_webhook_deliveries')
    op.drop_index(op.f('ix_store_sync_cursors_store_connection_id'), table_name='store_sync_cursors')
    op.drop_table('store_sync_cursors')
    op.drop_index(op.f('ix_store_capabilities_store_connection_id'), table_name='store_capabilities')
    op.drop_table('store_capabilities')
    op.drop_index(op.f('ix_products_workspace_id'), table_name='products')
    op.drop_index(op.f('ix_products_store_connection_id'), table_name='products')
    op.drop_index(op.f('ix_products_organization_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_store_connections_workspace_id'), table_name='store_connections')
    op.drop_index(op.f('ix_store_connections_organization_id'), table_name='store_connections')
    op.drop_table('store_connections')
    # ### end Alembic commands ###
