"""campaign_plan_items: add target_platform

Revision ID: d2065f1248fe
Revises: f61ea8a6eb45
Create Date: 2026-07-31 14:37:53.694823

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd2065f1248fe'
down_revision: str | Sequence[str] | None = 'f61ea8a6eb45'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaign_plan_items', sa.Column('target_platform', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaign_plan_items', 'target_platform')
    # ### end Alembic commands ###
