"""campaigns: add total_spent

Revision ID: f61ea8a6eb45
Revises: b5358aeb361b
Create Date: 2026-07-31 14:22:37.638363

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f61ea8a6eb45'
down_revision: str | Sequence[str] | None = 'b5358aeb361b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('total_spent', sa.Numeric(precision=14, scale=4), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaigns', 'total_spent')
    # ### end Alembic commands ###
